@startuml Domain Model
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
title <u>Domain Model - Concordia Campus Guide App - Version 1 (with annotations)</u>\n<i>Date : 2026-01-19 </i>\n<i>Author : Malak Sefrioui</i>
hide empty members

note as Scope
    <size:18><b><u>Scope :</u></b></size>
    This domain model covers main concepts/entities involved in a campus Navigation
    system for Concordia University. It includes classes for campuses, buildings,
    rooms, and points of interest (POIs) such as washrooms, elevators, stairs.
    These classes englobe the necessary concepts that will be needed throughout the
    future iterations/features of the system such as campuses and buildings for
    feature 1 (Show my location on campus) and Points of Interest for feature 5 
    (Find nearest POI).
end note

class "Terminal" as terminal {}

class "ClassCatalog" as ClassCatalog {
    - classes
}

class "Class" as Class {
    - courseCode
    - courseName
    - instructor
    - dayOfWeek
    - startTime
    - endTime
}

ClassCatalog "1" -- "*" Class : contains
Class "1" -- "1" Room : heldIn

note left of ClassCatalog
    <size:18><b><u>Class Scheduling Feature :</u></b></size>
    The ClassCatalog and Class classes have been added to the domain model
    to support the feature "Navigate me to my next class".
    The ClassCatalog will act as the schedule that contains all the classes
    a student is enrolled in. By naming convention "ObjectCatalog", instead
    of "Schedule", the name of the class remains consistent with the other
    catalog classes in the domain model.
end note

class "CampusCatalog" as CampusCatalog {
  - campuses
}

class "Campus" as Campus {
    - latitude
    - longitude
    - name
    - codename
    - buildings
}

class "BuildingCatalog" as Buildings {
-buildings
}
class "Building" as Building {
    - latitude
    - longitude
    - name
    - address
    - numberOfFloors
    - codename
    - indoors

}
class "Room" as Room {
    - latitude
    - longitude
    - roomNumber
    - capacity
    - floorNB
}
class "PointOfInterestCatalog" as PointOfInterestCatalog {
 
}

abstract class "PointOfInterest" as PointOfInterest {
    - latitude
    - longitude
}

abstract class "Indoor" as Indoor {

    - latitude
    - longitude
}

class "Washroom" as Washroom {
    - latitude
    - longitude
    - isPublic
    - isGenderNeutral
    - isMale
    - isFemale
    - isAccessible
    - floorNB
}
class "Elevator" as Elevator {
    - latitude
    - longitude
    - isAccessible
}
class "Stairs" as Stairs {
    - latitude
    - longitude
}
class "WaterFountain" as WaterFountain {
    - latitude
    - longitude
    - hasBottleFiller
    - floorNB
}

abstract class "Outdoor" as Outdoor {
    - address
    - name
    - type
    - latitude
    - longitude
}

class "Restaurant" as Restaurant {
    - latitude
    - longitude
    - cuisineType
    - address
    - name
    - type
}
class "CoffeeShop" as CoffeeShop {
    - latitude
    - longitude
    - address
    - name
    - type
}

terminal "1" -- "1" CampusCatalog : contains
terminal "1" -- "1" Buildings : contains
terminal "1" -- "1" PointOfInterestCatalog : contains
terminal "1" -- "1" ClassCatalog : contains

note top of terminal
    <size:18><b><u>Controller Design Pattern :</u></b></size>
    The terminal class will use a controller design pattern by which it
    will act as the interface of the system by receiving user inputs and
    will delegate the tasks to the appropriate catalog classes.
end note

note as Factory
    <size:18><b><u>Factory Design Pattern :</u></b></size>
    PointOfInterestCatalog will be using the factory design pattern
    to create different types of PointOfInterest objects within a 
    single method.
end note

note as Creators
    <size:18><b><u>Creators and Information Experts :</u></b></size>
    All the catalog classes (CampusCatalog, Buildings, 
    Rooms, PointOfInterestCatalog) take on the CREATOR 
    and INFORMATION EXPERT responsibilities from the 
    GRASP by being the classes responsible for the 
    creation of their respective objects and by finding objects
    based on some relevant attributes.
end note

Creators .. CampusCatalog
Creators .. Buildings
Creators .. PointOfInterestCatalog
Factory .. PointOfInterestCatalog

CampusCatalog "1" *-- "2" Campus : contains

Buildings "1" *-- "*" Building : contains

Campus "1" -- "*" Building : has

Building "1" -- "*" Indoor : has

PointOfInterestCatalog "1" *-- "*" PointOfInterest : contains

PointOfInterest <|-- Indoor
Indoor <|-- Washroom
Indoor <|-- Elevator
Indoor <|-- Stairs
Indoor <|-- WaterFountain
Indoor <|-- Room
PointOfInterest <|-- Outdoor
Outdoor <|-- Restaurant
Outdoor <|-- CoffeeShop

@enduml