@startuml Domain Model
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
title <u>Domain Model - Concordia Campus Guide App - Version 1 (with annotations)</u>\n<i>Date : 2026-01-19 </i>\n<i>Author : Malak Sefrioui</i>
hide empty members

note as Scope
    <size:18><b><u>Scope :</u></b></size>
    This domain model covers main concepts/entities involved in a campus Navigation
    system for Concordia University. It includes classes for campuses, buildings,
    rooms, and points of interest (POIs) such as washrooms, elevators, stairs.
    These classes englobe the necessary concepts that will be needed throughout the
    future iterations/features of the system such as campuses and buildings for
    feature 1 (Show my location on campus) and Points of Interest for feature 5 
    (Find nearest POI).
end note

class "Terminal" as terminal {}

class "CampusCatalog" as CampusCatalog {}
class "Campus" as Campus {
    - latitude: double
    - longitude: double
    - name: String
    - codename : String
}

class "BuildingCatalog" as Buildings {}
class "Building" as Building {
    - latitude: double
    - longitude: double
    - name: String
    - address: String
    - numberOfFloors: int
    - codename : String
}
class "Room" as Room {
    - roomNumber: String
    - capacity: int
    - floorNB: int
}
class "PointOfInterestCatalog" as PointOfInterestCatalog {}

abstract class "PointOfInterest" as PointOfInterest {}
abstract class "Indoor" as Indoor {
    - latitude: double
    - longitude: double
}

class "Washroom" as Washroom {
    - isPublic: boolean
    - isGenderNeutral: boolean
    - isMale: boolean
    - isFemale: boolean
    - isAccessible: boolean
    - floorNB: int
}
class "Elevator" as Elevator {
    - isAccessible: boolean
}
class "Stairs" as Stairs {
}
class "WaterFountain" as WaterFountain {
    - hasBottleFiller: boolean
    - floorNB: int
}

abstract class "Outdoor" as Outdoor {
    - latitude: double
    - longitude: double
    - address: String
    - name: String
    - type : String
}

class "Restaurant" as Restaurant {
    - cuisineType: String
}
class "CoffeeShop" as CoffeeShop {
}

terminal "1" -- "1" CampusCatalog
terminal "1" -- "1" Buildings
terminal "1" -- "1" PointOfInterestCatalog

note top of terminal
    <size:18><b><u>Controller Design Pattern :</u></b></size>
    The terminal class will use a controller design pattern by which it
    will act as the interface of the system by receiving user inputs and
    will delegate the tasks to the appropriate catalog classes.
end note

note as Factory
    <size:18><b><u>Factory Design Pattern :</u></b></size>
    PointOfInterestCatalog will be using the factory design pattern
    to create different types of PointOfInterest objects within a 
    single method.
end note

note as Creators
    <size:18><b><u>Creators and Information Experts :</u></b></size>
    All the catalog classes (CampusCatalog, Buildings, 
    Rooms, PointOfInterestCatalog) take on the CREATOR 
    and INFORMATION EXPERT responsibilities from the 
    GRASP by being the classes responsible for the 
    creation of their respective objects and by finding objects
    based on some relevant attributes.
end note

Creators .. CampusCatalog
Creators .. Buildings
Creators .. PointOfInterestCatalog
Factory .. PointOfInterestCatalog

CampusCatalog "1" *-- "2" Campus

Buildings "1" *-- "*" Building

Campus "1" -- "*" Building

Building "1" -- "*" Indoor

PointOfInterestCatalog "1" *-- "*" PointOfInterest

PointOfInterest <|-- Indoor
Indoor <|-- Washroom
Indoor <|-- Elevator
Indoor <|-- Stairs
Indoor <|-- WaterFountain
Indoor <|-- Room
PointOfInterest <|-- Outdoor
Outdoor <|-- Restaurant
Outdoor <|-- CoffeeShop

@enduml