// Static mapping of building codes to images
// IMPORTANT: require() paths must be static strings

export const BUILDING_IMAGES: Record<string, any> = {
  // SGW Buildings
  CC: require("../../../assets/buildings/CC_Building.jpg"),
  CJ: require("../../../assets/buildings/CJ_Building.jpg"),
  EV: require("../../../assets/buildings/EV_Building.jpg"),
  H: require("../../../assets/buildings/H_Building.jpg"),
  LB: require("../../../assets/buildings/LB_Building.jpg"),
  MB: require("../../../assets/buildings/MB_Building.jpg"),
  GM: require("../../../assets/buildings/GM_Building.jpg"),
  FB: require("../../../assets/buildings/FB_Building.jpg"),
  GS: require("../../../assets/buildings/GS_Building.jpg"),
  HC: require("../../../assets/buildings/HC_Building.jpg"),
  HB: require("../../../assets/buildings/HB_Building.jpg"),
  LD: require("../../../assets/buildings/LD_Building.jpg"),
  PC: require("../../../assets/buildings/PC_Building.jpg"),
  PS: require("../../../assets/buildings/PS_Building.jpg"),
  RA: require("../../../assets/buildings/RA_Building.jpg"),
  RF: require("../../../assets/buildings/RF_Building.jpg"),
  SC: require("../../../assets/buildings/SC_Building.jpg"),
  SH: require("../../../assets/buildings/SH_Building.jpg"),
  SP: require("../../../assets/buildings/SP_Building.jpg"),
  TA: require("../../../assets/buildings/TA_Building.jpg"),
  TD: require("../../../assets/buildings/TD_Building.jpg"),
  VA: require("../../../assets/buildings/VA_Building.jpg"),
  VE: require("../../../assets/buildings/VE_Building.jpg"),
  VL: require("../../../assets/buildings/VL_Building.jpg"),

  // Loyola Buildings
  AD: require("../../../assets/buildings/AD_Building.jpg"),
  CI: require("../../../assets/buildings/CI_Annex.jpg"),
  DO: require("../../../assets/buildings/DO.jpg"),
  ER: require("../../../assets/buildings/ER_Building.jpg"),
  FC: require("../../../assets/buildings/FC_Building.jpg"),
  FG: require("../../../assets/buildings/FG_Building.jpg"),
  GE: require("../../../assets/buildings/GE_Building.jpg"),
  GN: require("../../../assets/buildings/GN_Building.jpg"),
  HU: require("../../../assets/buildings/HU_Building.jpg"),
  JR: require("../../../assets/buildings/JR_Building.jpg"),
  LS: require("../../../assets/buildings/LS_Building.jpg"),
  MU: require("../../../assets/buildings/MU_Annex.jpg"),
  PT: require("../../../assets/buildings/PT_Building.jpg"),
  PY: require("../../../assets/buildings/PY_Building.jpg"),
  QA: require("../../../assets/buildings/QA.jpg"),
  SB: require("../../../assets/buildings/SB_Building.jpg"),
  SI: require("../../../assets/buildings/SI_Church.jpg"),

  // Annexes
  B: require("../../../assets/buildings/B_Annex.jpg"),
  BB: require("../../../assets/buildings/BB_Annex.jpg"),
  BH: require("../../../assets/buildings/BH_Annex.jpg"),
  CL: require("../../../assets/buildings/CL_Annex.jpg"),
  D: require("../../../assets/buildings/D_Annex.jpg"),
  EN: require("../../../assets/buildings/EN_Annex.jpg"),
  FA: require("../../../assets/buildings/FA_Annex.jpg"),
  GA: require("../../../assets/buildings/GA_Annex.jpg"),
  K: require("../../../assets/buildings/K_Annex.jpg"),
  M: require("../../../assets/buildings/M_Annex.jpg"),
  MI: require("../../../assets/buildings/MI_Annex.jpg"),
  P: require("../../../assets/buildings/P_Annex.jpg"),
  PR: require("../../../assets/buildings/PR_Annex.jpg"),
  Q: require("../../../assets/buildings/Q_Annex.jpg"),
  R: require("../../../assets/buildings/R_Annex.jpg"),
  RR: require("../../../assets/buildings/RR_Annex.jpg"),
  S: require("../../../assets/buildings/S_Annex.jpg"),
  T: require("../../../assets/buildings/T_Annex.jpg"),
  V: require("../../../assets/buildings/V_Annex.jpg"),
  X: require("../../../assets/buildings/X_Annex.jpg"),
  Z: require("../../../assets/buildings/Z_Annex.jpg"),
};
